customhost = "database-1.coohddpvv930.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "laijunwei-employee"
customregion = "us-east-1"
